version: "3.9"
services:
  backend:
    build:
      context: ./src
    container_name: rag-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
